const arrData = [
    {
        name:"sumit",
        class:"bca",
        rollno:9,
        desig:"devlop"
    },
    {
        name:"brijesh",
        class:"bca",
        rollno:8,
        desig:"devlop"
    },
    {
        name:"amit",
        class:"bca",
        rollno:2,
        desig:"devlop"
    },
    {
        name:"ammy",
        class:"bca",
        rollno:5,
        desig:"devlop"
    },
    {
        name:"kartik",
        class:"bca",
        rollno:3,
        desig:"devlop"
    },
    {
        name:"sahil",
        class:"bca",
        rollno:1,
        desig:"devlop"
    },
    {
        name:"bhanu",
        class:"bca",
        rollno:4,
        desig:"devlop"
    },
    {
        name:"manish",
        class:"bca",
        rollno:10,
        desig:"devlop"
    },
    {
        name:"suraj",
        class:"bca",
        rollno:6,
        desig:"devlop"
    },
    {
        name:"aarti",
        class:"7",
        rollno:7,
        desig:"devlop"
    }
]

export default arrData